[tox]
envlist = test_package, typechecks, stylechecks, lint
skipsdist = True

[testenv]
install_command = pip install {opts} {packages}

[testenv:test_package]
deps =
	-rrequirements/test_requirements.txt
    -rrequirements/torch_req.txt

setenv =
	PYTHONPATH=.
	PYTHONHASHSEED=0

commands=
	python nerf_app/train_model.py
	pytest \
	-s \
	-vv \
	{posargs:tests/}

[testenv:train]
envdir = {toxworkdir}/test_package
deps =
	{[testenv:test_package]deps}

setenv =
	{[testenv:test_package]setenv}

commands=
	python nerf_app/train_model.py \
	--batch-size 32 \
	--epochs 100 \
	--save-n-epochs 5 \
	--lr 0.001 \
	--exp-name test_o1

[testenv:vismodel]
envdir = {toxworkdir}/test_package
deps =
	{[testenv:test_package]deps}

setenv =
	{[testenv:test_package]setenv}

commands=
	python nerf_app/visualize_attn.py

[testenv:unittest]
envdir = {toxworkdir}/test_package

deps =
	{[testenv:test_package]deps}

commands = {posargs:pytest -s}

[testenv:typechecks]
envdir = {toxworkdir}/test_package

deps =
	{[testenv:test_package]deps}

commands = {posargs:mypy nerf_app}

[testenv:stylechecks]
envdir = {toxworkdir}/test_package

deps =
	{[testenv:test_package]deps}

commands = {posargs:flake8 nerf_app tests}

[testenv:lint]
envdir = {toxworkdir}/test_package

deps =
	{[testenv:test_package]deps}

commands =
	isort nerf_app tests
	black nerf_app tests
	mypy nerf_app
	flake8 nerf_app

[flake8]
exclude = .git,env, .ipynb
max-line-length = 90