package_name: nerf_model
save_file: "D:/ML_AI_DL_Projects/projects_repo/nerf/savedfigure"
#Define root directory
data_dir: "D:/ML_AI_DL_Projects/pytorch_nerf/"
alpha: 0.5

training_sample: 100
testimg_idx: 101
# Stratified option dict
strf_samp_option:
  n_samples: 64 # Number of spatial samples per ray
  perturb: True # If set, applies noise to sample positions
  inverse_depth: False # If set, samples points linearly in inverse depth
  near: 2.0 # plane
  far: 6.0 # plane

encoder:
  d_input: 3 # Number of input dimensions
  n_freqs: 10 # Number of encoding functions for samples
  log_space: True # If set, frequencies scale in log space
  use_viewdirs: True # If set, use view direction as input
  n_freqs_views: 4 # Number of encoding functions for views

model:
  d_filter:  128          # Dimensions of linear layer filters
  n_layers:  2            # Number of layers in network bottleneck
  skip:  []               # Layers at which to apply input residual
  use_fine_model:  True   # If set, creates a fine model
  d_filter_fine:  128     # Dimensions of linear layer filters of fine network
  n_layers_fine:  6       # Number of layers in fine network bottleneck

hierarchical_sampling:
  n_samples_hierarchical: 64   # Number of samples per ray
  perturb_hierarchical: False  # If set, applies noise to sample positions
  raw_noise_std: 0.0
  white_bkgd: False

optimizer:
  lr: 5e-4

training_config:
  n_iters: 10000
  batch_size: 1         # Number of rays per gradient step (power of 2)
  one_image_per_step: True   # One image per gradient step (disables batching)
  chunksize: 2           # Modify as needed to fit in GPU memory
  center_crop: True          # Crop the center of image (one_image_per_)
  center_crop_iters: 50      # Stop cropping center after this many epochs
  display_rate: 25          # Display test output every X epochs

early_stoping_config:
  warmup_iters: 100          # Number of iterations during warmup phase
  warmup_min_fitness: 10.0   # Min val PSNR to continue training at warmup_iters
  n_restarts: 10             # Number of times to restart if training stalls